version: "3.9"

services:
    app:
        container_name: app
        image: app
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "3000:3000"
        depends_on:
            - school-db
        command: ["./wait-for-it.sh", "school-db:3306", "--", "node", "./app.js"]
    school-db:
        container_name: school-db
        image: mysql:latest
        environment:
            MYSQL_DATABASE: 'school-db'
            MYSQL_ROOT_PASSWORD: '123456'
        ports:
            - "3308:3306"
        expose:
            - '3306'
        volumes:
            - school-db:/var/lib/mysql
            - ./migrations:/docker-entrypoint-initdb.d

volumes:
    school-db:

networks:
    communication: