-- MySQL Script generated by MySQL Workbench
-- Tue Apr 19 19:18:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema school-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema school-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `school-db` DEFAULT CHARACTER SET utf8 ;
USE `school-db` ;

-- -----------------------------------------------------
-- Table `school-db`.`CompañiaGas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school-db`.`CompañiaGas` (
  `nombre` INT NULL DEFAULT NULL,
  `idCompañia` INT NOT NULL AUTO_INCREMENT UNIQUE,
  PRIMARY KEY (`idCompañia`),
  UNIQUE INDEX `CompañiaGas_idCompañia_uindex` (`idCompañia` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `school-db`.`CilindroDeCompañia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school-db`.`CilindroDeCompañia` (
  `idCilindroDeCompañia` INT NOT NULL AUTO_INCREMENT UNIQUE,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `idCompañia` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idCilindroDeCompañia`),
  INDEX `compañiaGas_fk` (`idCompañia` ASC) VISIBLE,
  CONSTRAINT `compañiaGas_fk`
    FOREIGN KEY (`idCompañia`)
    REFERENCES `school-db`.`CompañiaGas` (`idCompañia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `school-db`.`GrupoFamiliar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school-db`.`GrupoFamiliar` (
  `idGrupoFamiliar` INT NOT NULL AUTO_INCREMENT UNIQUE,
  `idRepresentante` INT NULL DEFAULT NULL,
  `idIntegranteGrupoFamiliar` INT NULL DEFAULT NULL,
  `relacion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idGrupoFamiliar`),
  INDEX `representante_fk` (`idRepresentante` ASC) VISIBLE,
  INDEX `integranteGrupoFamiliar_fk` (`idIntegranteGrupoFamiliar` ASC) VISIBLE,
  CONSTRAINT `integranteGrupoFamiliar_fk`
    FOREIGN KEY (`idIntegranteGrupoFamiliar`)
    REFERENCES `school-db`.`Persona` (`idPersona`),
  CONSTRAINT `representante_fk`
    FOREIGN KEY (`idRepresentante`)
    REFERENCES `school-db`.`Representante` (`idRepresentante`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `school-db`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school-db`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT UNIQUE,
  `cedula` VARCHAR(20) NULL DEFAULT NULL,
  `fecha_de_nacimiento` DATETIME NULL DEFAULT NULL,
  `nombre` VARCHAR(80) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `observaciones` VARCHAR(45) NULL DEFAULT NULL,
  `Inmueble_idInmueble` INT NULL DEFAULT NULL,
  `GrupoFamiliar_idGrupoFamiliar` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idPersona`),
  INDEX `fk_Persona_Inmueble1_idx` (`Inmueble_idInmueble` ASC) VISIBLE,
  INDEX `fk_Persona_GrupoFamiliar1_idx` (`GrupoFamiliar_idGrupoFamiliar` ASC) VISIBLE,
  CONSTRAINT `fk_Persona_GrupoFamiliar1`
    FOREIGN KEY (`GrupoFamiliar_idGrupoFamiliar`)
    REFERENCES `school-db`.`GrupoFamiliar` (`idGrupoFamiliar`),
  CONSTRAINT `fk_Persona_Inmueble1`
    FOREIGN KEY (`Inmueble_idInmueble`)
    REFERENCES `school-db`.`Inmueble` (`idInmueble`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `school-db`.`Representante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school-db`.`Representante` (
  `idRepresentante` INT NOT NULL AUTO_INCREMENT UNIQUE,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idRepresentante`),
  INDEX `fk_Representante_Persona1_idx` (`Persona_idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_Representante_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `school-db`.`Persona` (`idPersona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `school-db`.`TipoDeInmueble`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school-db`.`TipoDeInmueble` (
  `idTipoDeInmueble` INT NOT NULL AUTO_INCREMENT UNIQUE,
  `tipo` VARCHAR(45) NULL DEFAULT NULL UNIQUE,
  PRIMARY KEY (`idTipoDeInmueble`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `school-db`.`Ubicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school-db`.`Ubicacion` (
  `idUbicacion` INT NOT NULL AUTO_INCREMENT UNIQUE,
  `direccion` VARCHAR(80) NULL DEFAULT NULL UNIQUE,
  PRIMARY KEY (`idUbicacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `school-db`.`Inmueble`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school-db`.`Inmueble` (
  `idInmueble` INT NOT NULL AUTO_INCREMENT UNIQUE,
  `numero` INT NULL DEFAULT NULL,
  `TipoDeInmueble_idTipoDeInmueble` INT NULL DEFAULT NULL,
  `Ubicacion_idUbicacion` INT NULL DEFAULT NULL,
  `Representante_idRepresentante` INT NOT NULL,
  PRIMARY KEY (`idInmueble`),
  INDEX `fk_Inmueble_TipoDeInmueble_idx` (`TipoDeInmueble_idTipoDeInmueble` ASC) VISIBLE,
  INDEX `fk_Inmueble_Ubicacion1_idx` (`Ubicacion_idUbicacion` ASC) VISIBLE,
  INDEX `fk_Inmueble_Representante1_idx` (`Representante_idRepresentante` ASC) VISIBLE,
  CONSTRAINT `fk_Inmueble_Representante1`
    FOREIGN KEY (`Representante_idRepresentante`)
    REFERENCES `school-db`.`Representante` (`idRepresentante`),
  CONSTRAINT `fk_Inmueble_TipoDeInmueble`
    FOREIGN KEY (`TipoDeInmueble_idTipoDeInmueble`)
    REFERENCES `school-db`.`TipoDeInmueble` (`idTipoDeInmueble`),
  CONSTRAINT `fk_Inmueble_Ubicacion1`
    FOREIGN KEY (`Ubicacion_idUbicacion`)
    REFERENCES `school-db`.`Ubicacion` (`idUbicacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `school-db`.`CilindroDeInmueble`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school-db`.`CilindroDeInmueble` (
  `idCilindroDeInmueble` INT NOT NULL AUTO_INCREMENT UNIQUE,
  `Inmueble_idInmueble` INT NULL DEFAULT NULL,
  `CilindroDeCompañia_idCilindroDeCompañia` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idCilindroDeInmueble`),
  INDEX `fk_CilindroDeInmueble_Inmueble1_idx` (`Inmueble_idInmueble` ASC) VISIBLE,
  INDEX `fk_CilindroDeInmueble_CilindroDeCompañia1_idx` (`CilindroDeCompañia_idCilindroDeCompañia` ASC) VISIBLE,
  CONSTRAINT `fk_CilindroDeInmueble_CilindroDeCompañia1`
    FOREIGN KEY (`CilindroDeCompañia_idCilindroDeCompañia`)
    REFERENCES `school-db`.`CilindroDeCompañia` (`idCilindroDeCompañia`),
  CONSTRAINT `fk_CilindroDeInmueble_Inmueble1`
    FOREIGN KEY (`Inmueble_idInmueble`)
    REFERENCES `school-db`.`Inmueble` (`idInmueble`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `school-db`.`Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school-db`.`Vehiculo` (
  `idVehiculo` INT NOT NULL AUTO_INCREMENT UNIQUE,
  `placa` VARCHAR(20) NULL DEFAULT NULL,
  `color` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idVehiculo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `school-db`.`VehiculoDeInmueble`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school-db`.`VehiculoDeInmueble` (
  `idVehiculoDeInmueble` INT NOT NULL AUTO_INCREMENT UNIQUE,
  `Inmueble_idInmueble` INT NULL DEFAULT NULL,
  `Vehiculo_idVehiculo` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idVehiculoDeInmueble`),
  INDEX `fk_VehiculoDeInmueble_Inmueble1_idx` (`Inmueble_idInmueble` ASC) VISIBLE,
  INDEX `fk_VehiculoDeInmueble_Vehiculo1_idx` (`Vehiculo_idVehiculo` ASC) VISIBLE,
  CONSTRAINT `fk_VehiculoDeInmueble_Inmueble1`
    FOREIGN KEY (`Inmueble_idInmueble`)
    REFERENCES `school-db`.`Inmueble` (`idInmueble`),
  CONSTRAINT `fk_VehiculoDeInmueble_Vehiculo1`
    FOREIGN KEY (`Vehiculo_idVehiculo`)
    REFERENCES `school-db`.`Vehiculo` (`idVehiculo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
